# Generated by Django 3.2.3 on 2021-05-23 08:10

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='ssh_host',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500)),
        ),
        migrations.AddField(
            model_name='credential',
            name='ssh_password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500)),
        ),
        migrations.AddField(
            model_name='credential',
            name='ssh_port',
            field=django_cryptography.fields.encrypt(models.DecimalField(decimal_places=0, max_digits=1, null=True)),
        ),
        migrations.AddField(
            model_name='credential',
            name='ssh_username',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200)),
        ),
    ]
