# Generated by Django 3.2.3 on 2021-05-23 08:13

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0002_auto_20210523_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='admin_password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500)),
        ),
        migrations.AddField(
            model_name='credential',
            name='admin_url',
            field=django_cryptography.fields.encrypt(models.URLField(blank=True)),
        ),
        migrations.AddField(
            model_name='credential',
            name='admin_username',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100)),
        ),
    ]
