# Generated by Django 3.2.3 on 2021-05-23 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0005_auto_20210523_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credential',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
